# Generated by Django 4.2.16 on 2024-11-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trail_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
