# Generated by Django 4.2.16 on 2024-11-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_trail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
