# Generated by Django 4.2.16 on 2024-11-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_id_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default='Ongoing', max_length=50),
        ),
    ]
