# Generated by Django 4.2.16 on 2025-05-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluido', 'Concluido')], default='Em andamento', max_length=50),
        ),
    ]
