# Generated by Django 4.2.16 on 2025-05-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='notification_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
