# Generated by Django 4.2.16 on 2024-11-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='name',
            field=models.CharField(default='Usuário Anônimo', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
