# Generated by Django 4.2.16 on 2024-11-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_login', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics/'),
        ),
    ]
