# Generated by Django 4.2.16 on 2024-11-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tela_login', '0004_remove_profile_bio_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
