# Generated by Django 4.2.16 on 2025-05-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_login', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_task_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
