# Generated by Django 4.2.16 on 2025-05-12 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tela_login', '0007_useractivity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together={('user', 'date')},
        ),
    ]
